### ISSUE TITLE
Suggestion: Use slugify() to create ID's instead of "toc-#"

### ISSUE THREAD

**Issue by bridgeport** [idiotWu/jQuery-TOC#4]
I've been using your great script in conjunction with "markdown-it-anchor," but I've had to move away from from the latter and use another markdown parser. That particular markdown extension added ID's to the headings, using stringjs's slugify function (or a custom derivative):
http://stringjs.com/#methods/slugify

Could you please consider adding 'slugify-like' generated ID's to your script instead of "toc-#" ID's?

Thanks.

**Comment by dolphin-wood** [comment]
It seems to require some other libs (eg slugify) to accomplish this. However I want to make this tiny script as simple as it can be. I would suggest you make your own fork and modify it as you wish ;)
